# Generated by Django 2.0.5 on 2019-10-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20191019_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendquery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendquery', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=100)),
                ('transid', models.ForeignKey(on_delete=models.CASCADE, to='users.Reports_Garbage')),
            ],
        ),
    ]
